# Generated by Django 6.0.2 on 2026-02-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_produto_categoria_produto_cidade_produto_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem_url',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
